services:
  backend:
    build: ./backend
    container_name: tecommerce-backend
    ports:
      - "8080:8080"

  frontend-web:
    build: ./frontend-web
    container_name: tecommerce-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend